# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name_plural': 'book copies'},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='e.g. 0545582970', max_length=13, primary_key=True, serialize=False),
        ),
    ]
