# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('book', 'customer')]),
        ),
    ]
