# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170125_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='renew_count',
            field=models.IntegerField(default=1),
        ),
    ]
