# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161128_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
    ]
