# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20170127_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbook',
            name='category',
            field=models.CharField(choices=[('R', 'Read'), ('C', 'Currently Reading'), ('W', 'Wants to Read')], default='C', max_length=1),
        ),
    ]
